### IMQAV

- Ingest
- Model
- Query
- Analyze
- Visualize

**Ingest**


Ingestion is a set of software engineering techniques to adapt high volumes of data that arrive rapidly (often via streaming).

- Kafka
- RabbitMQ
- Fluentd
- Sqoop
- kinesis (AWS)

**Model**

Modeling is a set of data architecture techniques to create data storage that is appropriate for a particular domain.

- Relational   
    - MySQL
    - Postgres
    - RDS (AWS)   
    
- Key Value   
    - Redis
    - Rlak
    - DynamoDB (AWS)   

- Columnar   
    - Casandra
    - HBase
    - RedShift(AWS)   
- Document
    - MongoBD
    - ElasticSearch
    - CouchBase    
- Graph   
    - Neo4j
    - ArangoDB
    

**Query**

Query refers to extracting data (from storage) and modifying that data to accomodate anomalies such as missing data.

- Batch   
    - MapReduce
    - Spark
    - Elastic MapReduce(AWS)   
- BatchSQL   
    - Hive
    - Presto
    - Drill   
- Streaming
    - Storm
    - Spark Streaming
    - Samza

**Analyze**

Analyze is a broad category that includes techniques from computer science, mathematical modeling, artificial intelligence, statistics and other disciplines.

**NumPy is included within 'Analyze'**

- Statistics   
    - SPSS
    - SAS
    - R
    - Statsmodels
    - SciPy
    - Pandas
- Optimization and mathematical modeling (SciPy and other libraries)
    - Linear, integer, Dynamic, Programming
    - Gradient and Lagrange methods
- Machine Learning
    - Batch
        - H2O
        - Mahout
        - SparkML
    - Interactive
         - scikit-learn

**Visualize**

Visualize refers to transforming data into visually attractive and informative formats.

- matplotlib
- seaborn
- bokeh
- pandas
- D3
- Tableau
- Leaflet
- Highcharts
- Kibana

### Create NumPy Arrays

In [12]:
import numpy as np

In [13]:
print(np.__version__)

1.19.2


In [14]:
my_list = [17, 0, 4, 5, 9]


In [15]:
my_list

[17, 0, 4, 5, 9]

In [16]:
my_array_from_list = np.array(my_list)
my_array_from_list


array([17,  0,  4,  5,  9])

In [17]:
my_array_from_list *10

array([170,   0,  40,  50,  90])

In [18]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference betn python and numpy data structures

In [19]:
my_tuple *6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [20]:
np.array(my_tuple) *6

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])

### Intrinsic NumPy array creation Numpy's methods

In [21]:
# numpy.arange
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
np.arange(10, 23) -10+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
len(np.arange(10, 23))

13

In [26]:
my_range_array = np.arange(10, 23)
my_range_array.size

13