**Data Types**

In [1]:
import numpy as np

**Ndarrays**

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.shape # this give the 3, : which means we have a 1-dimensional array of size 3

(3,)

In [8]:
#higher dimensional array example
b=np.array([[1,2,3], [4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape # this mean we have a 2 dimension array of size 3 or 2*3 table

(2, 3)

In [14]:
type(b)

numpy.ndarray

In [15]:
c=np.array(11)

In [17]:
type(c)

numpy.ndarray

In [19]:
print(c)

11


In [20]:
c

array(11)

In [21]:
c.shape

()

In [22]:
d= np.array([15])

In [23]:
type(d)

numpy.ndarray

In [24]:
print(d)

[15]


In [25]:
d.shape

(1,)

**Array and List**

In [33]:
list_a = [1,2,3,4,5,6]

In [34]:
len(list_a)

6

In [35]:
list_b = [[1,2,3],[4,5,6]]

In [36]:
len(list_b)

2

In [37]:
array_b = np.array([[1,2,3],[4,5,6]])

In [38]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])