In [10]:
import numpy as np
from math import *
import random

In [3]:
Lnp=np.array([8,9,1,2,4,3,7,6,11])
Llist=[0,3,5,1,7,9]


# Sorting  in Decreasing Order  with Numpy

In [4]:
# A First Trick to Sort in Decreasing Order   but with Numpy
L=-np.sort(-L) 
print(L)

[11  9  8  7  6  4  3  2  1]


In [5]:
# A Second Trick to Sort in Decreasing Order    
L=np.array([8,9,1,2,4,3,7,6,11])
L_copy = np.sort(L)[::-1]
print(L)
print(L_copy)

[ 8  9  1  2  4  3  7  6 11]
[11  9  8  7  6  4  3  2  1]


# Sorting  in Decreasing Order  without Numpy

In [16]:
L=[2,4,7,1,0,6,10] ;
sorted(L,reverse=True)

[10, 7, 6, 4, 2, 1, 0]

In [55]:
# Another Trick 
L= [3,2,1,4,5]
L.sort()
print(L)
L=L[::-1]
print(L)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


## Randomly Generation of an array  with Numpy

In [4]:
Capacity=100
L = np.array([ np.random.randint(1,Capacity) for i in range(Capacity) ])
#print(L)

## Randomly Generation of an array  without Numpy

In [34]:
Capacity=100
N=10
List = [random.randint(1, Capacity) for i in range(N) ]
print(L)

[81 77 15 47 71 62 11 41 17 29 33 75  6 62  4 94 44 84 52 46 20 29 88 85
 56 89 53 45 28 89 33 72 45 32 18 23 40 28 86 47 61 70 34 13 79 74 12 47
 93 31  1 31 23 39 24 58 39 79 25 34 80 83 67 78 34 92 33 60 89 48  4 38
 39 93 44 29 21 87 43 81 73 93 74 36  5 94 55 94 26 72 98 47 23 79 22 49
 81 62 29 54]


# Interlacing / Interweaving

In [ ]:
# With Numpy
# You have to rewrite  it without Numpy

In [4]:
def Interlacing(a, b):
    c = np.empty((a.size + b.size,), dtype=a.dtype)
    c[0::2] = a
    c[1::2] = b
    return c

In [8]:
L1=np.array([8,9,1,2,4,3,7,6,11])
print(len(L1))
L2=np.array([118,119,111,112,114,113,117,116])
L12=Interlacing(L1,L2)
print(len(L2))
print(L12)

9
8
[  8 118   9 119   1 111   2 112   4 114   3 113   7 117   6 116  11]


##  How to verify that a 1D array has the "same" values that a 2D array ?

In [14]:
# A LIST
L1=[442,
252,252,252,252,252,252,252,
127,127,127,127,127,
106,106,106,106,
85,84,46,
37,37,
12,12,12,
10,10,10,10,10,10,
9,9]

In [15]:
#A LIST OF LIST 
L2=[[442, 46, 12, 12, 12], 
             [252, 252, 10, 10], 
             [252, 252, 10, 10], 
             [252, 252, 10, 10], 
             [252, 127, 127, 9, 9], 
             [127, 127, 127, 106, 37], 
             [106, 106, 106, 85, 84, 37]]            

In [16]:
# A FLATTEN FUNCTION
def forfor(a):
    return [item for sublist in a for item in sublist]
print(forfor(L2))


[442, 46, 12, 12, 12, 252, 252, 10, 10, 252, 252, 10, 10, 252, 252, 10, 10, 252, 127, 127, 9, 9, 127, 127, 127, 106, 37, 106, 106, 106, 85, 84, 37]


In [17]:
L2=forfor(L2)

In [18]:
L1==L2

False

In [19]:
# BUT 
sorted(L1)==sorted(L2)

True

## Concatenation  of to Lists (without Numpy)

In [21]:
# 1st method 
L=[1,2,3,4]    
L.extend([5,6,7,8,9,10])
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [20]:
# 2d method 
L1=[1,2,3]
L2=[3,4,5]
L=L1+L2
print(L)

[1, 2, 3, 3, 4, 5]


##  Some tests: Testa & Testb

In [32]:
def Testa(n,a,b,c,Capacity):
    L=np.zeros(n,dtype=int)    
    L[[0]]=a
    L[[1]]=b
    L[[2]]=c    
    for i in range(3,n):
        L[[i]]=(L[[i-1]]+L[[i-2]])% Capacity        
    return L    

In [30]:
def Testb(n,a,b,c,Capacity):
    L=np.zeros(n,dtype=int)    
    L[[0]]=a
    L[[1]]=b
    L[[2]]=c    
    for i in range(3,n):
        L[[i]]=(L[[i-1]]+L[[i-2]]*L[[i-3]])% Capacity        
    return L    

In [35]:
# 
Capacity=100
n=10
a=51
b=27
c=23
Testa(n,a,b,c,Capacity)

array([51, 27, 23, 50, 73, 23, 96, 19, 15, 34])

In [36]:
# 
Capacity=100
n=10
a=51
b=27
c=23
Testb(n,a,b,c,Capacity)

array([51, 27, 23,  0, 21, 21, 21, 62,  3,  5])